services:
  db:
    build: 
      context: mysql/
      dockerfile: Dockerfile
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=hmm
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=hmm
    expose:
      - 3306
      - 33060
  wordpress:
    build: 
      context: wordpress/
      dockerfile: Dockerfile
    ports:
      - 80:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=hmm
      - WORDPRESS_DB_NAME=wordpress


## SET flag in wordpress/flag.sh


