version: "3"

services:    
  web:
    build:
      context: .
      dockerfile: .docker/Dockerfile-web
    image: webserver
    container_name: webserver
    restart: always
    hostname: webserver
    environment:
      ADMIN_PW: example-password  
      HOST: http://localhost
    ports:
      - "80:80"